name: league_of_legends_app
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^5.0.3
  flutter_triple: ^1.2.7+2
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  modular_test: ^2.0.0
  triple_test: ^1.0.0

flutter:
  uses-material-design: true
